# Generated by Django 5.1 on 2025-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
